---
- name: Update Elasticsearch Configuration File
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^network\\.host:', line: 'network.host: {{ inventory_hostname }}' }
    - { regexp: '^http\\.port:', line: 'http.port: {{ elasticsearch.http_port }}' }

- name: Enable and start Elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: yes
