---
    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - wget
        - software-properties-common

    - name: Add Elastic GPG key
      apt_key:
        url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
        state: present

    - name: Install Kibana
      apt:
        name: kibana
        state: latest

    - name: Configure Kibana
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^{{ item.key }}:'
        line: '{{ item.key }}: {{ item.value }}'
      loop:
        - { key: 'server.host', value: '0.0.0.0' }  # Allow external connections
        - { key: 'elasticsearch.hosts', value: 'http://localhost:9200' }  # Adjust if necessary

    - name: Enable and start Kibana service
      systemd:
        name: kibana
        enabled: yes
        state: started
